// PLACEHOLDER — this file is meant to be auto-generated by running the
// `install_x402_helper` tool inside the Commonsmade builder workspace.
// Written here only so this repo type-checks and documents the expected
// shape; replace with the real generated file before relying on it.
//
// Per platform guidance: call `x402Fetch(url, init)` where `url` is built
// from `env.COMMONS_X402_API_URL` — the helper attaches
// `Authorization: Bearer <COMMONS_X402_API_KEY>` and unwraps the x402
// payment envelope, so callers never touch the key directly.
export async function x402Fetch(url: string, init: RequestInit = {}): Promise<Response> {
  throw new Error(
    "commons-x402.ts is a placeholder — run install_x402_helper in the " +
      "Commonsmade builder to generate the real implementation."
  );
}
