// PLACEHOLDER — generated by running `install_x402_helper` inside the
// Commonsmade builder workspace. Written here only so this repo
// type-checks and documents the expected shape; replace with the real
// generated file before relying on it.
export async function x402Fetch(url: string, init: RequestInit = {}): Promise<Response> {
  throw new Error(
    "commons-x402.ts is a placeholder — run install_x402_helper in the " +
      "Commonsmade builder to generate the real implementation."
  );
}
